<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>52508ec3-a36c-462b-8de6-feee1cf829d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;email-icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div/div/div[2]/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4e892c6-2005-4ea5-879c-4434c3ee5225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/GmailIcon.svg</value>
      <webElementGuid>4f1f6073-5e8b-44c8-a63c-effcd955b44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32px</value>
      <webElementGuid>3121ec3e-4226-4258-ba59-bcd0daab88c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32px</value>
      <webElementGuid>076ff70e-b4ae-4ae2-b6a7-6849201e5671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>email-icon</value>
      <webElementGuid>ba546ea7-dbb6-490a-98b3-e84e7fa360e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;about__wrapper&quot;]/div[@class=&quot;about__card about__cardAbout&quot;]/div[@class=&quot;about__about-us gtc-about-us&quot;]/div[@class=&quot;about__about-us-txt&quot;]/div[@class=&quot;flex justify-center items-center mb-8&quot;]/div[@class=&quot;flex flex-row space-x-12 place-self-center&quot;]/div[@class=&quot;about__has-tooltip pt-1&quot;]/a[1]/img[1]</value>
      <webElementGuid>b520e5f7-2edb-48f5-ac1c-2583a7001b5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div/div/div[2]/div/div[2]/a/img</value>
      <webElementGuid>e03cb9c8-2e40-4aa1-98d7-69468aaa8bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='email-icon']</value>
      <webElementGuid>ce9b2fe0-41c8-434d-b58c-2d3cf4ab1dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>790f8bb8-7240-4726-a505-5606919d38fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/GmailIcon.svg' and @alt = 'email-icon']</value>
      <webElementGuid>09a2324c-604b-45f9-ba6a-a31e380efb9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
