<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kalkulator</name>
   <tag></tag>
   <elementGuidId>a0dd4dad-f353-4fea-a6e6-08fb8eea6f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.about__card.about__calc-kpr > a > button.basic-button__button-color--orange.basic-button__padding-size--padding-0.about__findLink > p.basic-button__text-style--white.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/a/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f29d78c1-e8a9-4794-8d39-510bdbadc6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>basic-button__text-style--white text-primary</value>
      <webElementGuid>024418fb-9282-4f61-a3f8-859420d61b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kalkulator</value>
      <webElementGuid>1162d593-1ebf-464e-9980-9868ce4fb810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;about__wrapper&quot;]/div[@class=&quot;about__card about__calc-kpr&quot;]/a[1]/button[@class=&quot;basic-button__button-color--orange basic-button__padding-size--padding-0 about__findLink&quot;]/p[@class=&quot;basic-button__text-style--white text-primary&quot;]</value>
      <webElementGuid>022586b6-735f-4745-bb68-724280307318</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/a/button/p</value>
      <webElementGuid>50f1a11e-08e1-415a-a47d-9817491c18d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Properti'])[1]/following::p[8]</value>
      <webElementGuid>2f2347ff-45a4-4397-b255-59b670b02c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Support'])[1]/following::p[8]</value>
      <webElementGuid>c0f5645f-392d-4f4a-a82a-056ae9bf39d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen'])[1]/preceding::p[4]</value>
      <webElementGuid>733d8ed2-b277-48f3-b2ff-88e79d1dea66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karyawan'])[1]/preceding::p[4]</value>
      <webElementGuid>aaced5d2-b650-4dd0-8959-fd62535e98e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kalkulator']/parent::*</value>
      <webElementGuid>7df06d12-d5e4-4784-9a89-1530dd332a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/button/p</value>
      <webElementGuid>5ed9c3c5-2ef4-4678-8912-66168f540764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kalkulator' or . = 'Kalkulator')]</value>
      <webElementGuid>e3e1aa7f-531a-4fa1-aca5-33b7954d3cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
