<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode_captchaInput</name>
   <tag></tag>
   <elementGuidId>2ac7613e-66b0-4eec-a11f-6ed5dc336d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#captchaInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='captchaInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>659aa902-f63a-47e2-934d-3b20b418544f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b96d112e-01bd-453a-96d5-6c1c9b371226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode</value>
      <webElementGuid>c742f77c-603e-4862-b91d-87db17306f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captchaInput</value>
      <webElementGuid>2443c04e-047c-490f-b9c8-336761dd1dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7ec299c4-8b22-4f5b-90d7-7cfcd1fa10c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>captchaInput</value>
      <webElementGuid>2b2b93b3-f8ce-4706-bd96-5015260ab475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox__shape__withShadow textbox__color__bg__transparent textbox__color__border__gray textbox__color__placeholder__gray</value>
      <webElementGuid>dd07899d-dada-41fd-b4bd-477ab232fa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>75d7ab89-1146-4b19-8e7e-6d5f54e6b110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;captchaInput&quot;)</value>
      <webElementGuid>f730bbc5-0b06-4932-93fb-22beb0d2ba14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='captchaInput']</value>
      <webElementGuid>632d8ba6-3d14-4cd8-9ec0-2806bbf006ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>bbce18db-e8a9-4635-a8cd-c58f552bbdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>31af9ffd-3be8-4027-9b49-8b899bb078ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan kode' and @name = 'captchaInput' and @id = 'captchaInput']</value>
      <webElementGuid>9ae23989-aace-48dd-8b2f-f6d0c86c0927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
