<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kirim</name>
   <tag></tag>
   <elementGuidId>0fb8ad7d-ad11-4595-968d-07e618e34092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.basic-button__text-style--white.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div/div[2]/div/div/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9a5bf176-b4af-48a5-8a54-30368c50fb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>basic-button__text-style--white text-primary</value>
      <webElementGuid>48f5a984-2fe0-4109-92f5-227ceedeceeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>23fe2164-7bc3-405c-a6bf-2d2a76668e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;forgot-pass__basePage&quot;]/div[1]/div[@class=&quot;forgot-pass__baseForm&quot;]/div[2]/div[@class=&quot;forgot-pass__form__bodyForm__base&quot;]/div[1]/div[@class=&quot;forgot-pass__form__bodyForm__formBase&quot;]/button[@class=&quot;basic-button__button-color--blue basic-button__width--full basic-button__padding-size--padding-1&quot;]/p[@class=&quot;basic-button__text-style--white text-primary&quot;]</value>
      <webElementGuid>bbf06f61-7999-41fc-beb5-cc605ed6438f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div/div[2]/div/div/div/button/p</value>
      <webElementGuid>69d46761-d3f2-4458-8c58-64590d363286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/following::p[2]</value>
      <webElementGuid>b965aec4-6e5d-4f6f-b6d7-273fdd22a4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open main menu'])[1]/following::p[12]</value>
      <webElementGuid>17ef80f4-6981-427b-8e25-dcf41982a6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim']/parent::*</value>
      <webElementGuid>19ebdc9e-ac82-4df8-b0cd-899b700cb704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/p</value>
      <webElementGuid>29c3f7a8-5f59-4bb2-babf-99cb62a664b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kirim' or . = 'Kirim')]</value>
      <webElementGuid>6d16e7c4-d83a-4128-be74-8650d2c04d7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
