<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Open main menu_navbar__imgLink</name>
   <tag></tag>
   <elementGuidId>423ede13-f0ae-4284-b1c8-7168f0c1ac62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.navbar__imgLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d79a8ed-2544-499f-a40a-029942f007b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__imgLink</value>
      <webElementGuid>5f49b23e-b785-4b0f-941b-4a3c659c4fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/logo.svg</value>
      <webElementGuid>ad2b060c-fc1d-4de2-b398-81ea54905b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f94afb53-c599-428a-b237-3cdf39a82224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar__wrapperNav&quot;]/div[@class=&quot;navbar__container&quot;]/a[1]/img[@class=&quot;navbar__imgLink&quot;]</value>
      <webElementGuid>13977070-f583-4018-a7e2-0c630c4644d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/a/img</value>
      <webElementGuid>9eeb598a-ec3b-41d3-a8b4-29bed60fb626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>0e1f5b43-29b1-4010-9d90-ea12ccf0e5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>35620ca5-54e7-41f1-bd98-aca5041407b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/logo.svg' and @alt = 'img']</value>
      <webElementGuid>764e8050-e041-4cc5-8401-d4fe574cb2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
