<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_month</name>
   <tag></tag>
   <elementGuidId>4e174c19-1f09-4844-ad74-281c1456f442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f279bd8-e485-49ce-ac02-8d2c4b86da98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>54406b4b-6d4e-4de1-80bd-21216dd740c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-date-picker__inputGroup__input react-date-picker__inputGroup__month react-date-picker__inputGroup__input--hasLeadingZero</value>
      <webElementGuid>92a311fa-d808-47e9-807e-ab4400059e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>577285b4-9ef0-476c-a127-56f7898eb6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>41e91013-a6c2-44c5-a030-1b6a0b95c749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>7ab460bf-303d-4501-bfe4-96916fb282ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1fa812e-5d92-4f65-b1f4-68b86e537937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>93daaa5e-cf25-41f4-9d3e-2254c31ae994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>--</value>
      <webElementGuid>ef931283-ef0a-4581-8aac-9ea47cb1986d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>65a3ac60-e13a-4ec9-a528-2635999a729a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[1]/div[2]/div[@class=&quot;profile__topWrapper&quot;]/div[@class=&quot;profile__wrapper gtc-side-menu&quot;]/div[@class=&quot;profile__sidemenu-children&quot;]/div[@class=&quot;profile-page__wrapper&quot;]/div[@class=&quot;profile-page__body-wrap gtc-profile-page-s&quot;]/div[2]/div[@class=&quot;profile-page__ttl-wrap mobile:grid-cols-1&quot;]/div[2]/div[2]/div[@class=&quot;react-date-picker react-date-picker--open react-date-picker--enabled&quot;]/div[@class=&quot;react-date-picker__wrapper&quot;]/div[@class=&quot;react-date-picker__inputGroup&quot;]/input[@class=&quot;react-date-picker__inputGroup__input react-date-picker__inputGroup__month react-date-picker__inputGroup__input--hasLeadingZero&quot;]</value>
      <webElementGuid>6ac7b6db-7b71-4ced-8da8-42d79a292a0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='month']</value>
      <webElementGuid>1cca5690-6967-4f1f-bd9e-28cec09c568d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[3]/div[2]/div[2]/div/div/div/input[3]</value>
      <webElementGuid>ba2ccaaf-aa5d-4e8d-996c-a8848c836bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>5385d3e3-7c3e-4f56-8cc7-40d790dbc676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'month' and @placeholder = '--' and @type = 'number']</value>
      <webElementGuid>2d3a7471-685c-4000-89ae-faed7d164971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
