<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat Lahir_pob</name>
   <tag></tag>
   <elementGuidId>32aa01d0-e015-4e6c-9806-c1ae1e3844c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pob&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6616263-3cbf-4550-aaff-2afd4601975a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>faca0ff7-4a13-46f4-bb29-7eea67868108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pob</value>
      <webElementGuid>35de9687-deb2-4033-a2ba-80d55334b980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>bfe4a374-6550-4412-a195-879fd563e994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray</value>
      <webElementGuid>595ee18c-bdab-4b04-8e2f-6609dbb05584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>84236ce3-c19b-4e37-9d6d-f20bb6c1b925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[1]/div[2]/div[@class=&quot;profile__topWrapper&quot;]/div[@class=&quot;profile__wrapper gtc-side-menu&quot;]/div[@class=&quot;profile__sidemenu-children&quot;]/div[@class=&quot;profile-page__wrapper&quot;]/div[@class=&quot;profile-page__body-wrap gtc-profile-page-s&quot;]/div[2]/div[@class=&quot;profile-page__ttl-wrap mobile:grid-cols-1&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-row gap-3&quot;]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/div[1]/input[@class=&quot;textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray&quot;]</value>
      <webElementGuid>49d02bb2-0b9e-4541-9f10-ef65eddcc187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[3]</value>
      <webElementGuid>1da3330a-cb24-4cdd-9bc1-aa873b54f25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>4f6079d0-144f-42b1-aa68-2adcd3de68c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>7a0c70bb-509b-4fac-9724-13f7a862b221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pob']</value>
      <webElementGuid>37583be3-a474-4bfa-a694-4592ddba651d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
