<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RT_rt</name>
   <tag></tag>
   <elementGuidId>265cab06-3362-4e93-ab40-92eb0d93c3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rt&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id=''])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cba50b65-6fe1-446f-afe0-881bcc69fc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d97d64d-35eb-4fa3-89e6-89b33043676a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RT</value>
      <webElementGuid>315400a9-0fa1-49ca-9558-7cd81da19bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rt</value>
      <webElementGuid>a689f4ac-7554-4f2a-820f-3024a4b4aa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c8e34e50-a1ae-4c4c-8c6f-238b48b9823c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray</value>
      <webElementGuid>e3d01cfa-7e59-46c2-a78b-e1da137541be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>ce602ba0-5fb0-4a7f-9ff1-3079a00666d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>0b938d39-82bf-4157-9f51-052d1318890a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[1]/div[2]/div[@class=&quot;profile__topWrapper&quot;]/div[@class=&quot;profile__wrapper gtc-side-menu&quot;]/div[@class=&quot;profile__sidemenu-children&quot;]/div[@class=&quot;profile-page__wrapper&quot;]/div[@class=&quot;profile-page__body-wrap gtc-profile-page-s&quot;]/div[2]/div[@class=&quot;profile-page__textbox-wrap mt-10&quot;]/div[@class=&quot;flex flex-row mobile:flex-col gap-4 mt-4&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-row gap-3&quot;]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/div[1]/input[@class=&quot;textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray&quot;]</value>
      <webElementGuid>febdda84-e775-45cc-8bef-e9b4f325b6de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id=''])[7]</value>
      <webElementGuid>04dfdf29-39b1-4172-a852-61da41276b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[5]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>76a59e07-8173-4f40-b0fb-a49fabfc7653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>5855f087-51ea-4756-a6ee-9a1807f1e48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'RT' and @name = 'rt']</value>
      <webElementGuid>50f2095f-4ce9-4d4d-a02b-b48c091b998a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
