<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_est12yopmail.com</name>
   <tag></tag>
   <elementGuidId>540081c9-eba5-47de-828a-7445f6580a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.navbar__profileName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div/div/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>505fcbc9-97d5-4e15-87c1-2d5ce5e1293d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__profileName</value>
      <webElementGuid>22d547c1-e9eb-46fb-bed8-6355dfd8d558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>est12@yopmail.com</value>
      <webElementGuid>9f64fd74-27b7-468e-9386-1f837603aa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar__wrapperNav&quot;]/div[@class=&quot;navbar__container&quot;]/div[@class=&quot;flex largePc:order-2 mobile:ml-auto mobile:mr-3 tab:ml-auto tab:mr-3&quot;]/div[1]/div[@class=&quot;navbar__wrapperAv&quot;]/button[@class=&quot;navbar__btnProfile&quot;]/p[@class=&quot;navbar__profileName&quot;]</value>
      <webElementGuid>5b75cc0e-0aa8-4711-ab96-4c8256c67060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div/div/div/button/p</value>
      <webElementGuid>fe0b8a78-7ae5-4028-ad6d-62a8a03d0b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::p[1]</value>
      <webElementGuid>4317d02c-b63b-47ad-8bee-8185feb5bf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada pemberitahuan baru'])[1]/following::p[1]</value>
      <webElementGuid>8531e212-cf67-433b-9308-b20a8072dd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properti Baru Dekat Kamu'])[1]/preceding::p[18]</value>
      <webElementGuid>9df3a2f7-3a5b-417b-99c7-0b39e2f20cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/preceding::p[19]</value>
      <webElementGuid>2deda93c-8078-4aa0-9ab6-61863c4947e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='est12@yopmail.com']/parent::*</value>
      <webElementGuid>3587d534-f96a-4919-a6fc-068be230d2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>c57af2d9-01d5-4fa3-9376-ac7ae0396fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'est12@yopmail.com' or . = 'est12@yopmail.com')]</value>
      <webElementGuid>6435ffd6-9c29-4526-902e-dbfdb8446c3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
