<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Profil</name>
   <tag></tag>
   <elementGuidId>cf4438e9-69ff-4f79-95ec-d83dc0228f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.dropdown-list__list--sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/div/div/div/div[2]/ul/li/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>36a44338-94ab-4559-977d-7f32022c40cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-list__list--sm</value>
      <webElementGuid>d6b605df-ef99-4e91-b244-05ccc4b74fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profil</value>
      <webElementGuid>d9aa8f8c-48c2-4d61-90b7-7824a515c51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar__wrapperNav&quot;]/div[@class=&quot;navbar__container&quot;]/div[@class=&quot;flex largePc:order-2 mobile:ml-auto mobile:mr-3 tab:ml-auto tab:mr-3&quot;]/div[1]/div[@class=&quot;navbar__wrapperAv&quot;]/div[@class=&quot;dropdown-list__wraperProfile block&quot;]/ul[@class=&quot;dropdown-list__listWrap&quot;]/li[1]/p[@class=&quot;dropdown-list__list--sm&quot;]</value>
      <webElementGuid>22c73e74-9323-4e75-a8c8-cc4296d29e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/div/div/div/div[2]/ul/li/p</value>
      <webElementGuid>c0eb5808-7312-4ea8-a3c9-c7fbebc9c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::p[2]</value>
      <webElementGuid>6bfd9905-964d-4914-af91-2068cf23886c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada pemberitahuan baru'])[1]/following::p[2]</value>
      <webElementGuid>0c832244-ef12-4cdc-9b05-1a45a3c46a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properti Baru Dekat Kamu'])[1]/preceding::p[17]</value>
      <webElementGuid>4b149892-d397-4414-966f-3e51b77de14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/preceding::p[18]</value>
      <webElementGuid>d7422c7d-9e60-4402-a0d3-49ff9cf6f149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Profil']/parent::*</value>
      <webElementGuid>efe74077-bf60-44dd-90d5-d937e4f5cd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
      <webElementGuid>23cadba9-7263-498c-9407-b308e8828fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Profil' or . = 'Profil')]</value>
      <webElementGuid>ecfc6b7b-8599-478f-94c0-9f135d152cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
