<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Simpan</name>
   <tag></tag>
   <elementGuidId>cf49b509-8bc9-4188-ab0e-72b9a299c090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div.profile-page__btn-wrap > button.basic-button__button-color--blue.basic-button__padding-size--padding-0.add-admin__btn-bottom--save > p.basic-button__text-style--white.text-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[8]/button[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c83c24c4-d941-4652-bde1-25f054367509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>basic-button__text-style--white text-primary</value>
      <webElementGuid>f63e1af8-ced4-414a-b127-ebbf86edb5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>c9f57186-4dac-4b5b-918d-5ed79f4fa890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[1]/div[2]/div[@class=&quot;profile__topWrapper&quot;]/div[@class=&quot;profile__wrapper gtc-side-menu&quot;]/div[@class=&quot;profile__sidemenu-children&quot;]/div[@class=&quot;profile-page__wrapper&quot;]/div[@class=&quot;profile-page__body-wrap gtc-profile-page-s&quot;]/div[2]/div[@class=&quot;profile-page__btn-wrap&quot;]/button[@class=&quot;basic-button__button-color--blue basic-button__padding-size--padding-0 add-admin__btn-bottom--save&quot;]/p[@class=&quot;basic-button__text-style--white text-primary&quot;]</value>
      <webElementGuid>23c1b2f1-0fc2-4ae0-8313-6044a89a56f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div[8]/button[2]/p</value>
      <webElementGuid>14e7957e-98e5-469c-b8b2-9597cb82ecc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::p[4]</value>
      <webElementGuid>75e9d4e8-2701-4195-b92f-99a9ef006051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/following::p[7]</value>
      <webElementGuid>c78a7243-cc47-40c3-8f66-ebfb2e4a7cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Pusat'])[1]/preceding::p[1]</value>
      <webElementGuid>b12857d5-fd2b-4b45-a684-3ad870bf51e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dukungan'])[1]/preceding::p[2]</value>
      <webElementGuid>9332c89a-14b5-405d-b6cf-5e5dd884b63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>99d2872e-c528-45f7-9b1e-ab50c8c44ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/p</value>
      <webElementGuid>73a97dd8-2ebb-4566-874b-8d270db7c17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>ca61454d-fce5-4b99-aef0-469694715f99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
