<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Open main menu_navbar__imgLink</name>
   <tag></tag>
   <elementGuidId>7df7d5b0-0165-4499-87f5-da2cae573809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.navbar__imgLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72917047-7053-4099-8d60-d9589187e43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar__imgLink</value>
      <webElementGuid>94382827-ed17-4d9a-9eed-7a79594826e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/logo.svg</value>
      <webElementGuid>14f82f27-0f77-417c-bd4d-d7544b2f3d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd27b85b-906b-42ed-917c-26c991817ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/nav[@class=&quot;navbar__wrapperNav&quot;]/div[@class=&quot;navbar__container&quot;]/a[1]/img[@class=&quot;navbar__imgLink&quot;]</value>
      <webElementGuid>d1ee7e69-280f-4298-9d0d-00635916528e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div/a/img</value>
      <webElementGuid>a075dac2-8647-420e-9904-c5fcc84ed023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>65ab22d1-f756-45b8-b27a-a8b6f5991cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>a08e8584-7219-4ef1-a9c7-43e92a82ed0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/logo.svg' and @alt = 'img']</value>
      <webElementGuid>7d24c1c6-f2b1-45d9-95b3-5e8f31013d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
