<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rumah</name>
   <tag></tag>
   <elementGuidId>6f82a010-ea4f-4b39-8d6e-311808caf3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div/div[3]/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01d3e464-157c-4ebb-99e0-224d44344d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-list__list</value>
      <webElementGuid>8bfcb410-42fe-4321-b6da-8098d628af23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rumah</value>
      <webElementGuid>a0eb2f57-2259-4c97-bfcd-8539583bf43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;landing-page__wrapper __dashboard-bg&quot;]/div[@class=&quot;landing-page__jumbotron&quot;]/div[@class=&quot;mt-[80px]&quot;]/div[@class=&quot;p-[30px] mobile:mr-[0px] tab:mr-[0px] largePc:mr-[20px] smallPc:mr-[20px] bg-white rounded-2xl&quot;]/div[@class=&quot;flex&quot;]/div[1]/div[@class=&quot;dropdown-list__wrapper&quot;]/div[@class=&quot;dropdown-list__listWrap&quot;]/div[@class=&quot;dropdown-list__list&quot;]</value>
      <webElementGuid>0708e3c9-6e59-4370-94e9-165f6938167b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div/div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>9211bd6d-4a03-4e33-9627-3e4e74ad07e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apartment'])[1]/following::div[1]</value>
      <webElementGuid>e77156c7-e92a-44f5-a79e-a72a26045f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[2]/following::div[2]</value>
      <webElementGuid>b08ce583-bb4a-4c11-bc54-51977cdc0104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ruko'])[1]/preceding::div[1]</value>
      <webElementGuid>cc46a505-9ba3-4fbd-b7b1-bf6612d0a840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Villa'])[1]/preceding::div[2]</value>
      <webElementGuid>af1ebac6-61c8-4c35-b28b-cef77e94c1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rumah']/parent::*</value>
      <webElementGuid>f05129b5-abbb-4ebf-9ca7-e3170905147c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>c910f46a-4fd7-4fd6-991e-ffb9abb05043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rumah' or . = 'Rumah')]</value>
      <webElementGuid>737c2b6a-b945-47a9-9486-381db817625b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
