<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E_textbox__shape__withoutShadow textb_ef0f28</name>
   <tag></tag>
   <elementGuidId>3dd8baa9-0e82-45f9-b3e0-b5998dbd71d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.textbox__shape__withoutShadow.textbox__shape__disablePadding.textbox__color__bg__transparent.textbox__color__border__none.textbox__color__placeholder__gray</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f4827f3-f9bd-4f64-9101-6b105f18ad94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1680b126-71e3-42e2-84c2-88de64274f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>* Cari lokasi, nama properti atau nama developer</value>
      <webElementGuid>08265b64-4e3a-46f5-98f6-220b3a1c94ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b07f1a4b-6682-4aab-8540-730dba875438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray</value>
      <webElementGuid>957fb1ea-1299-402d-a0e2-27c3eab6606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>71408c39-3a39-4fb4-8c68-9fbe9f72d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;landing-page__wrapper __dashboard-bg&quot;]/div[@class=&quot;landing-page__jumbotron&quot;]/div[@class=&quot;mt-[80px]&quot;]/div[@class=&quot;p-[30px] mobile:mr-[0px] tab:mr-[0px] largePc:mr-[20px] smallPc:mr-[20px] bg-white rounded-2xl&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-row gap-3&quot;]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/div[1]/input[@class=&quot;textbox__shape__withoutShadow textbox__shape__disablePadding textbox__color__bg__transparent textbox__color__border__none textbox__color__placeholder__gray&quot;]</value>
      <webElementGuid>9920bd1a-306b-4656-a272-c2f54c40cd2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='']</value>
      <webElementGuid>5879104d-30d0-4fdd-9ab5-4951bf78bd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>1b514205-ad1c-4bff-9c13-8760c776a24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c1937b80-e717-4cef-9dca-4d09fc8eee22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '* Cari lokasi, nama properti atau nama developer']</value>
      <webElementGuid>f05d39f5-ff8f-411d-949a-8211312ecca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
