<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_hargaRumah</name>
   <tag></tag>
   <elementGuidId>cdd7199a-3fba-40db-9f52-8220f833e415</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;hargaRumah&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='hargaRumah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7688f61-6bb8-4465-870a-d0ae5d6ad645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>133bf9df-9bb2-44a6-8908-6c52010c7382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>67d64a27-a3cd-4ba5-a480-565533afab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hargaRumah</value>
      <webElementGuid>c3447546-dc48-49bd-afda-2ba62a87ce24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-label__currency</value>
      <webElementGuid>4993b9cb-b4fb-4ccf-b260-1750fe78f62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20125d51-7a1c-4b9a-b177-aeaffd246464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;landing-page__hww-calc-wrapper&quot;]/div[@class=&quot;prod-detail__pages__property__detailBuying__left__detailCard__wrapper&quot;]/div[@class=&quot;landing-page calc-kpr__wrapper&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[1]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/input[@class=&quot;textbox-label__currency&quot;]</value>
      <webElementGuid>997e65db-be57-4fc5-8f1e-b9f8ff9c4408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='hargaRumah']</value>
      <webElementGuid>20caf3bb-075b-4008-be92-fcdc92e812fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div[6]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e2eccb2a-0ba8-4651-8f21-78674576ea19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>16b3084d-ce75-49a1-80b4-8bba3a114af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'hargaRumah' and @placeholder = '0']</value>
      <webElementGuid>6ba93953-4251-4984-9c25-4322ee0f842a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
