<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_dp</name>
   <tag></tag>
   <elementGuidId>73d3b969-d9f0-4d30-b8dd-85356b97bc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dp&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9a1a193-e3cf-4d95-b241-04c12e7ffcd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d85d4c36-9fd6-4cbb-8600-0c24dc78d51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>7462a2c9-ea8e-487f-9abf-62bd10012fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dp</value>
      <webElementGuid>38801ded-1944-4430-91d9-fb0a19584d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-label__currency</value>
      <webElementGuid>6449e370-d7b3-4fc6-ab4e-5f7f829a43dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5e2494e-de94-4be9-994a-ca0fea4dd6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>998e8f3c-c6af-433b-9ffc-bd954c74e214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;landing-page__hww-calc-wrapper&quot;]/div[@class=&quot;prod-detail__pages__property__detailBuying__left__detailCard__wrapper&quot;]/div[@class=&quot;landing-page calc-kpr__wrapper&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[1]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/input[@class=&quot;textbox-label__currency&quot;]</value>
      <webElementGuid>d57e2c71-e899-4e78-89bb-ed20d4bd869f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dp']</value>
      <webElementGuid>070c3683-5b4b-4803-9685-e4a4a30d49bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div[6]/div/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>c7fe23b7-78dc-4f05-b865-d9e9909f8f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>16437b8c-49bf-4ff7-9cf8-22d0f328e82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dp' and @placeholder = '0']</value>
      <webElementGuid>9a2355c2-c34c-41b8-9820-354e69e2eb6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
