<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suku Bunga_fixedRate</name>
   <tag></tag>
   <elementGuidId>d530ec15-d9fa-42ed-9d29-220f781aae8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fixedRate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fixedRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dccf9f9-0ed3-4c6a-9593-1e656e970384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-label__currency</value>
      <webElementGuid>f1c7367b-218d-4f85-8ce3-ed39d07c72f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>79b8782c-2505-4059-b369-a2e23ca1ea70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fixedRate</value>
      <webElementGuid>ae44b329-06eb-4380-86a8-e78f17f3a2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rightlabel</name>
      <type>Main</type>
      <value>%</value>
      <webElementGuid>01bb3810-50ad-44e6-a347-950d45b97dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>cc03ebef-e17d-4099-a58c-365edfd6a270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[6]/div[@class=&quot;landing-page__hww-calc-wrapper&quot;]/div[@class=&quot;prod-detail__pages__property__detailBuying__left__detailCard__wrapper&quot;]/div[@class=&quot;landing-page calc-kpr__wrapper&quot;]/div[2]/div[@class=&quot;textbox-label__wrapper&quot;]/div[@class=&quot;textbox-label__textboxWrapper&quot;]/input[@class=&quot;textbox-label__currency&quot;]</value>
      <webElementGuid>56478873-5235-49ad-adcc-565e04004d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fixedRate']</value>
      <webElementGuid>cb71d7d1-7cc5-45e1-a02d-491148198c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div[6]/div/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>b5aac620-b78a-4d5d-a4fc-6c8956b048b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>44c83ee1-bab7-405b-b642-b1317f5cd061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '0' and @name = 'fixedRate']</value>
      <webElementGuid>508611b2-a7a4-468e-abec-f6df33cb18a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
